// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeqN_pFNu7wo7sgXKs96WokTet_M5Gfxk',
    appId: '1:1024207682658:android:20c1aef46e054e7071e53b',
    messagingSenderId: '1024207682658',
    projectId: 'informacioncamionetas-44aae',
    databaseURL: 'https://informacioncamionetas-44aae-default-rtdb.firebaseio.com',
    storageBucket: 'informacioncamionetas-44aae.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWD5sJ0Rjtz-qPgAIbaPjQDrJFHIZfvbY',
    appId: '1:1024207682658:web:bd9939456d4255c971e53b',
    messagingSenderId: '1024207682658',
    projectId: 'informacioncamionetas-44aae',
    authDomain: 'informacioncamionetas-44aae.firebaseapp.com',
    databaseURL: 'https://informacioncamionetas-44aae-default-rtdb.firebaseio.com',
    storageBucket: 'informacioncamionetas-44aae.firebasestorage.app',
  );
}
