// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeqN_pFNu7wo7sgXKs96WokTet_M5Gfxk',
    appId: '1:1024207682658:android:20c1aef46e054e7071e53b',
    messagingSenderId: '1024207682658',
    projectId: 'informacioncamionetas-44aae',
    databaseURL: 'https://informacioncamionetas-44aae-default-rtdb.firebaseio.com',
    storageBucket: 'informacioncamionetas-44aae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClTQ-QCaHXqC-6K-v_S1eFdZLwKQuif-k',
    appId: '1:1024207682658:ios:980d7170743f027471e53b',
    messagingSenderId: '1024207682658',
    projectId: 'informacioncamionetas-44aae',
    databaseURL: 'https://informacioncamionetas-44aae-default-rtdb.firebaseio.com',
    storageBucket: 'informacioncamionetas-44aae.firebasestorage.app',
    iosBundleId: 'com.example.vistaCamionetas',
  );
}
